# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

# Generates binaries for windows, linux (x64, arm) and macos

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./TerminalPilot
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Publish (Linux Arm64)
      run: dotnet publish --runtime linux-arm64
    - name: Publish (Linux x64)
      run: dotnet publish --runtime linux-amd64
    - name: Publish (Windows x64)
      run: dotnet publish --runtime win-x64
    - name: Publish (macOS)
      run: dotnet publish --runtime osx-x64
    - name: Upload Artifact (Windows x64)
      uses: actions/upload-artifact@v4
      with:
        name: TerminalPilot - Windows
        path: |
          .\TerminalPilot\bin\Debug\net6.0\win-x64\publish*
    - name: Upload Artifact (Linux Arm64)
      uses: actions/upload-artifact@v4
      with:
        name: TerminalPilot - Linux Arm64
        path: |
          .\TerminalPilot\bin\Debug\net6.0\linux-arm64\publish*
    - name: Upload Artifact (Linux x64)
      uses: actions/upload-artifact@v4
      with:
        name: TerminalPilot - Linux x64
        path: |
          .\TerminalPilot\bin\Debug\net6.0\linux-x64\publish*
    - name: Upload Artifact (MacOS)
      uses: actions/upload-artifact@v4
      with:
        name: TerminalPilot - MacOS
        path: |
          .\TerminalPilot\bin\Debug\net6.0\linux-x64\publish*
